version: '2'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  frontend:
    image: frontend:latest
    networks:
      default:
        aliases:
          - frontend

  backend:
    image: backend:latest
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}
    hostname: dev
    networks:
      default:
        aliases:
          - backend

  router:
    image: router:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

networks:
  default:
