version: "2"
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"

  frontend:
    image: ${REGISTRY}frontend:${FRONTEND_VERSION}
    restart: always
    networks:
      default:
        aliases:
          - frontend

  backend:
    image: ${REGISTRY}backend:${BACKEND_VERSION}
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}
      - REDIS_URL=redis://${REDIS_HOST}
    hostname: dev
    networks:
      default:
        aliases:
          - backend

  router:
    image: ${REGISTRY}router:${ROUTER_VERSION}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

networks:
  default:
